FORMAT: 1A

# Group Origins

## Origin [/v1/depot/origins/{name}]
Origins are rad.

+ Parameters
  + name: `lulz` (string)

+ Attributes (object)
  + id: 123456 (string, required)
  + name: awesomefuntimes (string, required)
  + owner_id: 456789 (string)
  + private_key_name: haha (string)
  + default_package_visibility: public (string)

### Retrieve an Origin [GET]

+ Request (application/json)

+ Response 200 (application/json)
  + Attributes (Origin)

